name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]

env:
  SSH_USER: ${{ secrets.SSH_USER }}
  SSH_KEY: ${{ secrets.SSH_KEY }}
  SSH_HOST: ${{ secrets.SSH_HOST }}
  SSH_PORT: ${{ secrets.SSH_PORT }}

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: My first action
        shell: bash
        run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - name: check system variables
        run: echo " user ${{ secrets.SSH_USER }} port ${{ secrets.SSH_PORT }}"

