name: Production
run-name: ${{ github.actor }} deploying ${{ vars.TARGET_DOMAIN }} to production
on:
  push:
    branches:
      - main
jobs:
  deploy:
    environment: NorthWeb.dev - PROD
    name: "Triggering Remote Deployer"
    runs-on: ubuntu-latest
    # needs: test
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/staging.key
          cat ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host staging
            HostName $SSH_HOST
            User $SSH_USER
            Port $SSH_PORT
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_PORT: ${{ secrets.SSH_PORT }}

      - name: Check out the source
        run: ssh staging "cd deployer && ./deploy.sh ${{ vars.TARGET_DOMAIN }}"


